"""
This type stub file was generated by pyright.
"""

register = ...
@register.filter
def admin_urlname(value, arg): # -> LiteralString:
    ...

@register.filter
def admin_urlquote(value): # -> str:
    ...

@register.simple_tag(takes_context=True)
def add_preserved_filters(context, url, popup=..., to_field=...): # -> Literal[b""]:
    ...

