"""
This type stub file was generated by pyright.
"""

from django.template.library import InclusionNode

class InclusionAdminNode(InclusionNode):
    """
    Template tag that allows its template to be overridden per model, per app,
    or globally.
    """
    def __init__(self, parser, token, func, template_name, takes_context=...) -> None:
        ...
    
    def render(self, context): # -> SafeString:
        ...
    


