"""
This type stub file was generated by pyright.
"""

def no_append_slash(view_func): # -> _Wrapped[..., Any, ..., CoroutineType[Any, Any, Any]]:
    """
    Mark a view function as excluded from CommonMiddleware's APPEND_SLASH
    redirection.
    """
    ...

