"""
This type stub file was generated by pyright.
"""

def shortcut(request, content_type_id, object_id): # -> HttpResponseRedirect:
    """
    Redirect to an object's page based on a content-type ID and an object ID.
    """
    ...

