"""
This type stub file was generated by pyright.
"""

from django.contrib.admin.decorators import action
from django.utils.translation import gettext_lazy

"""
Built-in, globally-available admin actions.
"""
@action(permissions=["delete"], description=gettext_lazy("Delete selected %(verbose_name_plural)s"))
def delete_selected(modeladmin, request, queryset): # -> TemplateResponse | None:
    """
    Default action which deletes the selected objects.

    This action first displays a confirmation page which shows all the
    deletable objects, or, if the user has no permission one of the related
    childs (foreignkeys), a "permission denied" message.

    Next, it deletes all selected objects and redirects back to the change list.
    """
    ...

