"""
This type stub file was generated by pyright.
"""

def check_admin_app(app_configs, **kwargs): # -> list[Any]:
    ...

def check_dependencies(**kwargs): # -> list[Any]:
    """
    Check that the admin's dependencies are correctly installed.
    """
    ...

class BaseModelAdminChecks:
    def check(self, admin_obj, **kwargs): # -> list[Error | Any]:
        ...
    


class ModelAdminChecks(BaseModelAdminChecks):
    def check(self, admin_obj, **kwargs): # -> list[Error | Any]:
        ...
    


class InlineModelAdminChecks(BaseModelAdminChecks):
    def check(self, inline_obj, **kwargs): # -> list[Error | Any]:
        ...
    


def must_be(type, option, obj, id): # -> list[Error]:
    ...

def must_inherit_from(parent, option, obj, id): # -> list[Error]:
    ...

def refer_to_missing_field(field, option, obj, id): # -> list[Error]:
    ...

