"""
This type stub file was generated by pyright.
"""

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

class AdminAuthenticationForm(AuthenticationForm):
    """
    A custom authentication form used in the admin app.
    """
    error_messages = ...
    required_css_class = ...
    def confirm_login_allowed(self, user): # -> None:
        ...
    


class AdminPasswordChangeForm(PasswordChangeForm):
    required_css_class = ...


