# Generated by Django 5.2.4 on 2025-08-05 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(default='Patient', editable=False, max_length=10)),
                ('identifier_use', models.CharField(blank=True, choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temp'), ('secondary', 'Secondary')], max_length=20)),
                ('identifier_system', models.URLField(blank=True)),
                ('identifier_value', models.CharField(blank=True, max_length=100)),
                ('name_use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temp'), ('nickname', 'Nickname'), ('anonymous', 'Anonymous'), ('old', 'Old'), ('maiden', 'Maiden')], default='usual', max_length=20)),
                ('family_name', models.CharField(max_length=100)),
                ('given_names', models.JSONField(default=list)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('telecom_phone', models.CharField(blank=True, max_length=20)),
                ('telecom_email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('birth_date', models.DateField()),
                ('address_use', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('billing', 'Billing')], max_length=20)),
                ('address_line', models.JSONField(default=list)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_district', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
